In [16]:
import pandas as pd

In [17]:
year = 1961

In [18]:
df = pd.read_csv(f"{year}-stops-localised-final.csv")

In [19]:
df_initial = pd.read_csv(f"../initial/line_data_{year}.csv")

In [20]:
# Create a dictionary to map stop names to their respective east-west values
stop_to_east_west = {}
for index, row in df_initial.iterrows():
    stops = row['Stops'].split(' - ')
    for stop in stops:
        stop_to_east_west[stop] = row['east-west']

# Create the east-west column in df
df['east-west'] = df['stop_name'].apply(lambda x: stop_to_east_west.get(x, 'Unknown'))

print(df[['stop_name', 'east-west']])

                                 stop_name east-west
0                                  4. Ring      West
1                              Adamstrasse      West
2                                Adlershof       Ost
3                      Adolf-Scheidt-Platz      West
4                        Afrikanische Str.      West
...                                    ...       ...
1375                   Zoologischer Garten      West
1376                      Zossener Strasse      West
1377  Zossener Strasse Ecke Blücherstrasse      West
1378                        Zum Heckeshorn      West
1379                   ZweiBrücker Strasse      West

[1380 rows x 2 columns]

In [21]:
# Check for invalid values in the 'east-west' column
invalid_values = df[~df['east-west'].isin(['Ost', 'West'])]

# Print the rows with invalid values
print(invalid_values)

      Unnamed: 0                                          stop_name  \
38            38                                           Am Fließ
81            81                Baumschulenstrasse Ecke Südostallee
124          124                                  Bhf. Groß Ziethen
194          194                                      Blumenstrasse
201          201                                   Borsigwalder Weg
299          299                                            Dorfaue
314          314                                         Eichendamm
348          348                                     Fasanenstrasse
418          418                                      Goethestrasse
563          563                          Judenstrasse, Molkenmarkt
653          653                              Krankenhause Neukölln
715          715                                     Lerchenstrasse
721          721  Lichtenrade, Blohmstrasse Ecke Wünsdorfer Strasse
817          817                                  Nettelbeckstrasse
836          836                                    Oberhofer Platz
893          893                                               Post
998          998                        Rüdersdorf, Karl-Marx-Platz
999          999                        Rüdersdorf, Thälmannstrasse
1008        1008                             S-Bhf. Friedrichshagen
1009        1009                             S-Bhf. Friedrichshagen
1026        1026                                   S-Bhf. Rahnsdorf
1076        1076                             Schöneiche, Goethepark
1187        1187                                      Thälmannplatz
1188        1188                                      Thälmannplatz
1302        1302  Weißensee, Liebermannstrasse Ecke Piesporter S...
1314        1314               Wichertstrasse Ecke Prenzlauer Allee
1356        1356                             Woltersdorfer Schleuse

              type                                location  \
38             bus    52.6034575714732, 13.289613652822638
81             bus   52.46095841731415, 13.481191835004426
124            bus   52.39427199849872, 13.442667394442617
194            bus   52.44932599725309, 13.759715132008731
201            bus    52.58482847787268, 13.29793542584195
299            bus    52.47886105131975, 13.70053232372426
314            bus   52.45563928691219, 13.730601143973864
348            bus  52.452960838046685, 13.744604216761394
418            bus  52.455522709275314, 13.725374316281378
563   strassenbahn  52.516142213164905, 13.410591792750504
653   strassenbahn   52.43977054074335, 13.459359057866306
715            bus   52.45518873071384, 13.734268401558374
721            bus   52.38867704828861, 13.394344156462488
817            bus  52.501073025698915, 13.346723829543516
836            bus   52.42410259117963, 13.328170432694991
893            bus   52.47029587176764, 13.786537970773646
998            bus  52.468598623083736, 13.791633300477105
999            bus   52.474663106849825, 13.77362632033625
1008           bus   52.45731046148184, 13.625536519339297
1009  strassenbahn                   52.4564126,13.6253656
1026           bus  52.451628368326396, 13.691579101298974
1076           bus   52.470798548586494, 13.68835638892532
1187           bus   52.45066904252597, 13.752260000383929
1188        u-bahn                       52.51167,13.38472
1302           bus   52.56056756076504, 13.477555745782263
1314           bus    52.54571094901922, 13.42782494047603
1356           bus    52.4427723984596, 13.764524016423056

                                               in_lines identifier east-west
38                                                  A15        NaN   Unknown
81                                                  A47        NaN   Unknown
124                                                  AZ        NaN   Unknown
194   S-Bhf. Rahnsdorf <> Woltersdorfer Schleuse (VE...        NaN      Ost
201                                                 A15        NaN   Unknown
299   S-Bhf. Friedrichshagen <> Rüdersdorf, Karl-Mar...        NaN      Ost
314   S-Bhf. Rahnsdorf <> Woltersdorfer Schleuse (VE...        NaN      Ost
348   S-Bhf. Rahnsdorf <> Woltersdorfer Schleuse (VE...        NaN      Ost
418   S-Bhf. Rahnsdorf <> Woltersdorfer Schleuse (VE...        NaN      Ost
563                                                  71        NaN   Unknown
653                                                  47        NaN   Unknown
715   S-Bhf. Rahnsdorf <> Woltersdorfer Schleuse (VE...        NaN      Ost
721                                                 AS2        NaN   Unknown
817                                                 A69        NaN   Unknown
836                                                 A17        NaN   Unknown
893   S-Bhf. Friedrichshagen <> Rüdersdorf, Karl-Mar...        NaN      Ost
998   S-Bhf. Friedrichshagen <> Rüdersdorf, Karl-Mar...        NaN      Ost
999   S-Bhf. Friedrichshagen <> Rüdersdorf, Karl-Mar...        NaN      Ost
1008  S-Bhf. Friedrichshagen <> Rüdersdorf, Karl-Mar...        NaN      Ost
1009                                              84,87  Q66360784      Ost
1026  A22,S-Bhf. Rahnsdorf <> Woltersdorfer Schleuse...        NaN      Ost
1076  S-Bhf. Friedrichshagen <> Rüdersdorf, Karl-Mar...        NaN      Ost
1187  S-Bhf. Rahnsdorf <> Woltersdorfer Schleuse (VE...        NaN      Ost
1188                                                  A    Q658391      Ost
1302                                                A55        NaN   Unknown
1314                                                A56        NaN   Unknown
1356  S-Bhf. Rahnsdorf <> Woltersdorfer Schleuse (VE...        NaN      Ost

In [23]:
invalid_values

,Unnamed: 0,stop_name,type,location,in_lines,identifier,east-west
38,38,Am Fließ,bus,"52.6034575714732, 13.289613652822638",A15,NaN,Unknown
81,81,Baumschulenstrasse Ecke Südostallee,bus,"52.46095841731415, 13.481191835004426",A47,NaN,Unknown
124,124,Bhf. Groß Ziethen,bus,"52.39427199849872, 13.442667394442617",AZ,NaN,Unknown
194,194,Blumenstrasse,bus,"52.44932599725309, 13.759715132008731",S-Bhf. Rahnsdorf <> Woltersdorfer Schleuse (VE...,NaN,Ost
201,201,Borsigwalder Weg,bus,"52.58482847787268, 13.29793542584195",A15,NaN,Unknown
299,299,Dorfaue,bus,"52.47886105131975, 13.70053232372426","S-Bhf. Friedrichshagen <> Rüdersdorf, Karl-Mar...",NaN,Ost
314,314,Eichendamm,bus,"52.45563928691219, 13.730601143973864",S-Bhf. Rahnsdorf <> Woltersdorfer Schleuse (VE...,NaN,Ost
348,348,Fasanenstrasse,bus,"52.452960838046685, 13.744604216761394",S-Bhf. Rahnsdorf <> Woltersdorfer Schleuse (VE...,NaN,Ost
418,418,Goethestrasse,bus,"52.455522709275314, 13.725374316281378",S-Bhf. Rahnsdorf <> Woltersdorfer Schleuse (VE...,NaN,Ost
563,563,"Judenstrasse, Molkenmarkt",strassenbahn,"52.516142213164905, 13.410591792750504",71,NaN,Unknown
653,653,Krankenhause Neukölln,strassenbahn,"52.43977054074335, 13.459359057866306",47,NaN,Unknown
715,715,Lerchenstrasse,bus,"52.45518873071384, 13.734268401558374",S-Bhf. Rahnsdorf <> Woltersdorfer Schleuse (VE...,NaN,Ost
721,721,"Lichtenrade, Blohmstrasse Ecke Wünsdorfer Strasse",bus,"52.38867704828861, 13.394344156462488",AS2,NaN,Unknown
817,817,Nettelbeckstrasse,bus,"52.501073025698915, 13.346723829543516",A69,NaN,Unknown
836,836,Oberhofer Platz,bus,"52.42410259117963, 13.328170432694991",A17,NaN,Unknown
893,893,Post,bus,"52.47029587176764, 13.786537970773646","S-Bhf. Friedrichshagen <> Rüdersdorf, Karl-Mar...",NaN,Ost
998,998,"Rüdersdorf, Karl-Marx-Platz",bus,"52.468598623083736, 13.791633300477105","S-Bhf. Friedrichshagen <> Rüdersdorf, Karl-Mar...",NaN,Ost
999,999,"Rüdersdorf, Thälmannstrasse",bus,"52.474663106849825, 13.77362632033625","S-Bhf. Friedrichshagen <> Rüdersdorf, Karl-Mar...",NaN,Ost
1008,1008,S-Bhf. Friedrichshagen,bus,"52.45731046148184, 13.625536519339297","S-Bhf. Friedrichshagen <> Rüdersdorf, Karl-Mar...",NaN,Ost
1009,1009,S-Bhf. Friedrichshagen,strassenbahn,"52.4564126,13.6253656","84,87",Q66360784,Ost
1026,1026,S-Bhf. Rahnsdorf,bus,"52.451628368326396, 13.691579101298974","A22,S-Bhf. Rahnsdorf <> Woltersdorfer Schleuse...",NaN,Ost
1076,1076,"Schöneiche, Goethepark",bus,"52.470798548586494, 13.68835638892532","S-Bhf. Friedrichshagen <> Rüdersdorf, Karl-Mar...",NaN,Ost
1187,1187,Thälmannplatz,bus,"52.45066904252597, 13.752260000383929",S-Bhf. Rahnsdorf <> Woltersdorfer Schleuse (VE...,NaN,Ost
1188,1188,Thälmannplatz,u-bahn,"52.51167,13.38472",A,Q658391,Ost
1302,1302,"Weißensee, Liebermannstrasse Ecke Piesporter S...",bus,"52.56056756076504, 13.477555745782263",A55,NaN,Unknown
1314,1314,Wichertstrasse Ecke Prenzlauer Allee,bus,"52.54571094901922, 13.42782494047603",A56,NaN,Unknown
1356,1356,Woltersdorfer Schleuse,bus,"52.4427723984596, 13.764524016423056",S-Bhf. Rahnsdorf <> Woltersdorfer Schleuse (VE...,NaN,Ost